name: Bug report
description: Report a crash or bug
title: "[BUG] "
labels:
  - bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Brief & clear description of the bug or crash
    validations:
      required: true
   - type: textarea
     id: reproduction-steps
     attributes:
       label: Steps to reproduce
       description: Tell us the steps to reproduce the bug
     validations:
       required: true
