name: Bug report
description: Report a crash or bug
title: "[Bug]: "
labels:
  - bug
body:
  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: Brief & clear description of the bug or crash
    validations:
      required: true
